# Intentional dummy secret-like values are used in these unit tests
# to verify masking behavior; keep exclusions tightly scoped.
paths-ignore:
  - "tests/unit/test_logger.py"
  - "tests/unit/test_structured_logger.py"
  - "tests/unit/test_config_manager.py"
